### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MoonOutput'

### ISSUE THREAD

**Issue by camel007** [tornadomeet/mxnet-face#30]
I have cloned the 'face' branch, but still get this error?

INFO:root:Namespace(batch_size=384, data_dir='./', gpus='0', kv_store='local', list_dir='/data/celeba_dababase/moon_mxnet/im2rec/', lr=0.05, model_load_epoch=0, model_load_prefix='../model/lightened_moon/lightened_moon', model_save_prefix='../model/lightened_moon/lightened_moon_fuse', num_examples=159923, retrain=False)
Traceback (most recent call last):
  File "lightened_moon.py", line 147, in <module>
    main()
  File "lightened_moon.py", line 74, in main
    symbol = lightened_moon(num_classes=40, use_fuse=True)
  File "lightened_moon.py", line 69, in lightened_moon
    moon = mx.symbol.MoonOutput(data=fc2, src_dist_path='./src_dict.txt', name='Moon')
AttributeError: 'module' object has no attribute 'MoonOutput'

**Comment by xingdi1990** [comment]
Same error

**Comment by wiwatarm** [comment]
same error :(

**Comment by shuizhilinxin** [comment]
same error，who can help me？thanks

**Comment by Ndron** [comment]
https://github.com/tornadomeet/mxnet-face/issues/53
