### ISSUE TITLE
Unable to perform Attribute Detetction

### ISSUE THREAD

**Issue by mridulbirla** [tornadomeet/mxnet-face#37]
The attribute prediction script is failing at the following lline( I have downloaded the model).

 _, arg_params, aux_params = mx.model.load_checkpoint(args.model_load_prefix, args.model_load_epoch)

Traceback (most recent call last):
  File "predict.py", line 83, in <module>
    main()
  File "predict.py", line 14, in main
    _, arg_params, aux_params = mx.model.load_checkpoint(args.model_load_prefix, args.model_load_epoch)
  File "/home/mridul/anaconda3/lib/python3.5/site-packages/mxnet/model.py", line 372, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/mridul/anaconda3/lib/python3.5/site-packages/mxnet/symbol.py", line 1056, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/mridul/anaconda3/lib/python3.5/site-packages/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op Moon of type MoonOutput: [02:02:41] src/core/op.cc:55: Che

**Comment by feliu** [comment]
+1

**Comment by christinahartw** [comment]
+1

**Comment by christinahartw** [comment]
Has anyone figured this out?

**Comment by ccc013** [comment]
I do this:
git clone --brach face --recursive git@github.com:tornadomeet/mxnet.git
make -j8
cd python
python setup.py install 

then i can use the attribute prediction code to predict attributions

**Comment by quanh** [comment]
+1

**Comment by xingdi1990** [comment]
I did as what you did, but still not running the code. @ccc013

**Comment by anandbhattad** [comment]
Does anyone have a solution installing it for GPU version?

**Comment by leoliu37** [comment]
I also fail to detect attributes. And the slightly changed mxnet branch link isn't available.
